### ISSUE TITLE
All Installed And Working vGPU compatibility

### ISSUE THREAD

**Issue by jimthedj65** [alexhaydock/zfs-on-wsl#3]
Hi Alex, and thanks for the ZFS kernel with the penguins rule :-) Not an issue as such, but do you know of a way to boot the Microsoft kernel and use your kernel in parallel? like a multi-boot in the config?

I am configuring turbojpeg and using Nvidia Cuda cores with vGPU to accelerate X applications?

Since running your kernel it locks me out of the Nvidia vGPU with the error 'Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system'

Which is misleading to a config or version error but is down to not having the standard MS kernel installed.

Any pointers are greatly appreciated, and thanks for a great implementation with ZFS I got my 12.4TB of media files loaded as a share out to windows and retained my ZFS setup.  All it took was 

1. sudo zpool import -f ${pool}
2. sudo zpool import -f media
3. sudo zpool status 
4. 21.8TB came online..

**Comment by alexhaydock** [comment]
Fantastic @jimthedj65! Glad to hear you got it working and thanks for including the details of the version you're on. I've not had the best success with every Windows version so it's useful to know.

I actually didn't know you could use multiple kernels at once since I thought there was just a single Hyper-V VM that WSL2 spawned in the background, and that all open Linux instances would use that VM.

Glad to hear you've got it working since I was wondering how I'd troubleshoot this as I don't have any NVidia hardware to test with!

Out of interest - what kernel version and ZFS version did you get working? I assume you bumped the old version numbers in vars.sh before using this since they're pretty old now.
